app = "transcendence-lite-backend"
primary_region = "fra"

[build]
  dockerfile = "backend/Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

